name: finazaap
description: "A new Flutter project."
#publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2
  intl: ^0.19.0
  settings_ui: ^2.0.2
  flutter_colorpicker: ^1.0.3
  syncfusion_flutter_charts: ^28.2.7
  async: ^2.11.0
  boolean_selector: ^2.1.1
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.18.0
  fake_async: ^1.3.1
  http_parser: ^4.0.2
  image_picker_for_web: ^3.0.6
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  matcher: ^0.12.16+1
  material_color_utilities: ^0.11.1
  month_year_picker: ^0.4.0+1
  meta: ^1.15.0
  mime: ^2.0.0
  path: ^1.9.0
  stack_trace: ^1.11.1
  string_scanner: ^1.2.0
  syncfusion_flutter_core: ^28.2.7
  vm_service: ^14.3.1
  responsive_navigation_bar: ^5.0.2
  # Añadir esta dependencia
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  test_api: ^0.7.4
  animated_float_action_button: ^1.0.4
  animated_bottom_navigation_bar: ^1.3.3
  flutter_floating_bottom_bar: ^1.2.1
  font_awesome_flutter: ^10.7.0
  radial_button: ^1.0.1
  flutter_expandable_fab: ^2.3.0
  build_runner: ^2.3.3  # Añadir esta línea
  hive_generator: ^2.0.0  # Añadir esta línea si no está presente

flutter:
  uses-material-design: true